print("hi there, what is your name")
input("")
print("hello(name), welcome to CT8")
print("i am going to tell you a story about soccer try outs")
print("")
print("")
vehicle =input ("pick a vehicle:   ")
location = input("now pick a location:   ")
print("~~~*~~~*~~~*~~~*~~~*")
sport = input ("now pick a sport:  ")
numbers = input("pick two numbers:   ")
print(f"One day, i took a {vehicle} to soccer try outs, the try outs were in {location} once we got there we played {sport} adn the score was {numbers} ")
